#!/bin/bash
LG3DHOME=/home/kirk/src/lg3d/stable/0.5.1/lg3d

LG_SETTINGS="${LG_SETTINGS} -Dlg.etcdir=${LG3DHOME}/etc/"

if [ "$LGX11HOME" == "" ]
then
  LGX11HOME=${LG3DHOME}/ext/lg3d-x11
fi

if [ "$LGCORESRC" == "" ]
then
  LGCORESRC=${LG3DHOME}/src
fi

CLASSPATH="${LG3DHOME}/lib/ext/lg3d-core.jar:${LG3DHOME}/"
for arg in `ls ${LG3DHOME}/ext/*.jar`
do
  CLASSPATH="$CLASSPATH:$arg"
done
LD_LIBRARY_PATH="${LG3DHOME}/lib/i386:${LD_LIBRARY_PATH}"

#PATH="${JAVA_HOME}/bin:$PATH"

DISPLAY=":0.0"

RMI_PORT=44817

CONFIG="lgconfig_1p_nox.xml"
LGCONFIG="file://${LG3DHOME}/etc/lg3d/${CONFIG}"
 
echo ${CLASSPATH}
CLASSPATH=".:$CLASSPATH"

java -cp ${CLASSPATH} ${LG_SETTINGS} -Dlg.configurl=${LGCONFIG} $1
